defaults:
  - _self_
  - override hydra/launcher:  local
  - override hydra/output:  local


# snapshot
save_snapshot: True
load_snap: ""
# replay buffer
num_workers: 16
batch_size: 32 #256
train_steps: 500000
eval_freq: 20000
# misc
seed: 1
device: cuda
# experiment
experiment: train_mcr
# agent
lr: 1e-4
# data
alpha: 0.2
dataset: "libero" # "droid" # "ego4d"
use_wandb: false
wandbproject: 
wandbuser: 
doaug: "rctraj"
datapath: '/media/jhshin/PortableSSD/libero'
view_list:
  - obs/agentview_rgb
  - obs/eye_in_hand_rgb
  # - exterior_image_1_left
  # - exterior_image_2_left
  # - wrist_image_left\
tasks:
  # - libero_90
  - libero_goal
  # - libero_object
  # - libero_spatial

agent:
  _target_: mcr.MCR
  device: ${device}
  lr: ${lr}
  hidden_dim: 1024
  size: 50 #34
  tcnweight: 1.0
  l2dist: true
  bs: ${batch_size}
  align_state_weight: 1.0
  state_window: 3 # must be odd
  use_action: True
  state_list:
    # - cartesian_position
    # - gripper_position
    - obs/ee_states
    - obs/gripper_states
    - obs/joint_states
  bc_weight: 1.0